# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Courses/ENEL373/projects/ALUProject/ALUProject.cache/wt [current_project]
set_property parent.project_path C:/Courses/ENEL373/projects/ALUProject/ALUProject.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib {
  C:/Courses/ENEL373/projects/ALUProject/ALUProject.srcs/sources_1/imports/new/Ddecoder.vhd
  C:/Courses/ENEL373/projects/ALUProject/ALUProject.srcs/sources_1/imports/new/my_ALU.vhd
  C:/Courses/ENEL373/projects/ALUProject/ALUProject.srcs/sources_1/new/Project_File.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Courses/ENEL373/projects/ALUProject/ALUProject.srcs/constrs_1/imports/ALUProject/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files C:/Courses/ENEL373/projects/ALUProject/ALUProject.srcs/constrs_1/imports/ALUProject/Nexys4DDR_Master.xdc]


synth_design -top Project_File -part xc7a100tcsg324-3


write_checkpoint -force -noxdef Project_File.dcp

catch { report_utilization -file Project_File_utilization_synth.rpt -pb Project_File_utilization_synth.pb }
